# baseURL
@baseURL = https://code.seholee.com:8082

###
GET {{baseURL}}

###
# User Signup
POST {{ baseURL }}/users
Content-Type: application/json

{
    "uid": "example@email.com",
    "name": "로그인예제",
    "serviceNumber": "123456789",
	"password": "password"
}

###
# User Login
POST {{ baseURL }}/auth/login
Content-Type: application/json

{
    "uid": "seho0808",
	"password": "!1q2w3e4r"
}

###
# User Logout
POST {{ baseURL }}/logout
Content-Type: application/json
