# baseURL
@baseURL = https://code.seholee.com:8082

###
GET {{baseURL}}

###
# User Signup
POST {{ baseURL }}/users
Content-Type: application/json
    "uid": "tester3",
    "name": "로그인예제3",
    "serviceNumber": "33333333",
	"password": "tester3"
}

###
# User Login
POST {{ baseURL }}/auth/login
Content-Type: application/json

{
    "uid": "example@email.com",
    "password": "password"
}

###
# User Logout
GET {{ baseURL }}/auth/logout
Content-Type: application/json

###
# Delete Test
DELETE {{ baseURL }}/users/4
Content-Type: application/json