# baseURL
@baseURL = https://code.seholee.com:8082

###
GET {{baseURL}}

###
# User Signup
POST {{ baseURL }}/users
Content-Type: application/json

{
    "uid":"ehdwlsdudwo1a",
    "password":"password!!",
    "name":"임동진",
    "serviceNumber":"22-760010211",
    "enlistmentDate":"2023-02-11T15:00:00.000Z",
    "affiliatedUnit":"계룡대근무지원단",
    "militaryRank":"일병"
}

###
# User Login
POST {{ baseURL }}/auth/login
Content-Type: application/json

{
    "uid": "seho0808",
	"password": "!1q2w3e4r"
}

###
# User Logout
POST {{ baseURL }}/logout
Content-Type: application/json
