# baseURL
@baseURL = http://localhost:8081
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsIm5hbWUiOiLtmY3quLjrj5kiLCJzZXJ2aWNlTnVtYmVyIjoiMjItNzY3NiIsImlhdCI6MTY2NTg0OTUwNSwiZXhwIjoxNjY1ODY3NTA1fQ.yT4P-MH_BNaafaEElVdAD8ZTwOKxtwDLDvU9dcWEIKI
###
# Find All Users
GET {{ baseURL }}/users

###
# Find User By Id
GET {{ baseURL }}/users/1

###
# Create User
POST {{ baseURL }}/users
Content-Type: application/json

{
    "uid": "dkeim",
	"password": "1234",
    "name": "keim d",
    "serviceNumber": "12k22223n",
    "enlistmentDate": "2022-12-31T00:00:00.000Z",
    "affiliatedUnit": "an",
    "militaryRank": "aj"
}

###
# Modify User By Id
POST {{ baseURL }}/auth/login
Content-Type: application/json

{
    "uid": "123",
	"password": "123"
}

###
# Delete User By Id
DELETE {{ baseURL }}/users/1

###
GET {{ baseURL }}/chatroom/commander/13
Authorization: Bearer {{ token }}
