# baseURL
@baseURL = http://localhost:8081

###
# Find All Users
GET {{ baseURL }}/users

###
# Find User By Id
GET {{ baseURL }}/users/1

###
# Create User
POST {{ baseURL }}/users
Content-Type: application/json

{
    "uid": "dkeim",
	"password": "1234",
    "name": "keim d",
    "serviceNumber": "12k22223n",
    "enlistmentDate": "2022-12-31T00:00:00.000Z",
    "affiliatedUnit": "an",
    "militaryRank": "aj"
}

###
# Modify User By Id
PUT {{ baseURL }}/users/1
Content-Type: application/json

{
    "email": "123",
	"password": "p123"
}

###
# Delete User By Id
DELETE {{ baseURL }}/users/1
